- name: package is uploaded
  ansible.builtin.copy:
    src: app-cache/{{app.jarfile}}
    dest: /opt/apps/

- name: service is defined
  ansible.builtin.template:
    src: "templates/app-service.service.j2"
    dest: /etc/systemd/system/{{app_name}}.service
  notify:
    - "Systemd is reloaded"
  register: service_definition

- name: service is enabled and started
  ansible.builtin.systemd_service:
    name: "{{app_name}}"
    enabled: true
    state: "{{ (service_definition is changed)|ternary('restarted', 'started') }}"